#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# Enable main features. Possible values: true | false (default = false)
#
enabled: true

# A history window length in seconds to track player moving, possible values: 2 ... 100
moving_history_window: 60

#
# A share of time (in percents) the player runs in one direction
# during the history window
# that triggers an Illusioner.
#
# 80% of Sprinting = 104% of Walking, so Walking is safe.
#
# Possible values: 0.0001 ... 1000.
#
# A value of more than 100 requires the player to move faster than running.
#
run_share_to_trigger: 80.0

#
# A length of history to project the player move history, possible values: 2 ... 100.
#
# Must be less than "moving_history_window".
#
move_projection_history_length: 4

#
# A minimum distance of the player move history needed to project the player move history.
#
# Possible values: 0.0001 ... 1000.
#
# Must be less than "move_projection_distance".
#
move_projection_min_history_distance: 0.1

# A distance to project the player move history, possible values: 0.0001 ... 1000
move_projection_distance: 30.0

#
# Max distance between the player and the existing illusioner until it has to be moved closer.
#
# Possible values: 0.0001 ... 1000.
#
max_distance_to_existing_illusioner: 50.0

#
# A probability (in percents) that in the current second
# an Illusioner will be triggered.
#
# 5.0 = 5% = 1/20
#
# Possible values: 0.0001 ... 100.0.
#
per_second_trigger_probability: 2.0