name: NastyIllusioner
main: com.gmail.uprial.nastyillusioner.NastyIllusioner
version: 0.6.0
api-version: 1.19
commands:
  nastyillusioner:
      description: Reload NastyIllusioner config
      usage: /nastyillusioner help
      permission:
      permission-message:
permissions:
  nastyillusioner.reload:
    description: Gives access to NastyIllusioner 'reload' command
    default: op
  nastyillusioner.info:
    description: Gives access to NastyIllusioner 'info [@player]' command
    default: op
  nastyillusioner.reset:
    description: Gives access to NastyIllusioner 'reset [@player]' command
    default: op